#!/usr/bin/env php
<?php

if (count($argv) < 3) {
    fprintf(STDERR, "Usage: {$argv[0]} <hostname> <port_number>\n");
    exit(1);
}

$sleep_duration = 1;
$retries = 10;

$host = $argv[1];
$port = $argv[2];
$server = "{$host}:{$port}";
$socket = null;

for (;;) {
    echo "Checking for {$server} readiness, {$retries} tries remaining\n";
    $socket = @fsockopen($host, $port);

    if ($socket !== FALSE) {
        break;
    }

    echo "Could not connect to {$server}, retrying in {$sleep_duration}s\n";
    sleep($sleep_duration);
    $sleep_duration *= 2;
    $retries -= 1;

    if ($retries <= 0) {
        echo "Failed to connect to {$server}\n";
        exit(2);
    }
}

fclose($socket);
echo "✓ Connected to {$server}\n";
