#!/usr/bin/env ruby

require 'socket'

if ARGV.length != 2
  puts "Usage: #{PROGRAM_NAME} <hostname> <port_number>"
  exit 1
end

sleep_duration = 1
retries = 10

host = ARGV[0]
port = ARGV[1]
server = "#{host}:#{port}"

begin
  puts "Checking for #{server} readiness, #{retries} tries remaining"
  s = TCPSocket.new(host, port)
rescue Errno
  puts "Could not connect to #{server}, retrying in #{sleep_duration}s"
  sleep(sleep_duration)
  sleep_duration *= 2
  retries -= 1
  retry if retries > 0

  puts "Failed to connect to #{server}"
  exit 2
ensure
  s.close unless s.nil?
end

puts "✓ Connected to #{server}"
